language: node_js

node_js:
  - 8

before_install:
  - npm i -g npm@6.2.0
  - npm i -g lerna

install:
  - lerna bootstrap
  - lerna run build

jobs:
  include:
    - stage: "lint"
      name: "eslint"
      script: npm run eslint

stages:
  - lint
